version: 0.2

phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - echo "Fetching secrets from AWS Secrets Manager"
      - aws secretsmanager get-secret-value --secret-id MyAppDatabaseCredentials --query SecretString --output text > secret.json
      - export $(cat secret.json | jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]')
      - rm secret.json
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo "Build completed on `date`"
artifacts:
  files:
    - '**/*'
